-- Supabase Schema for Last-Scout

-- Artists table
CREATE TABLE IF NOT EXISTS artists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    is_core BOOLEAN DEFAULT false,
    bandsintown_patch TEXT,
    linktree_url TEXT,
    last_linktree_snapshot TEXT,
    priority_level TEXT,
    last_checked TIMESTAMP WITH TIME ZONE
);

-- Events table
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist TEXT NOT NULL,
    city TEXT NOT NULL,
    venue TEXT NOT NULL,
    date DATE NOT NULL,
    ticket_url TEXT,
    is_recommendation BOOLEAN DEFAULT false,
    source TEXT,
    is_proximity BOOLEAN DEFAULT false,
    UNIQUE(artist, city, date)
);

-- Similar Artists Cache table
CREATE TABLE IF NOT EXISTS similar_artists_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_artist_id BIGINT REFERENCES artists(id) ON DELETE CASCADE,
    similar_artist_name TEXT NOT NULL,
    match_score FLOAT,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
