-- Supabase Schema for Last-Scout

-- Artists table
CREATE TABLE IF NOT EXISTS artists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    is_core BOOLEAN DEFAULT false
);

-- Events table
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist TEXT NOT NULL,
    city TEXT NOT NULL,
    venue TEXT NOT NULL,
    date DATE NOT NULL,
    ticket_url TEXT,
    is_recommendation BOOLEAN DEFAULT false,
    UNIQUE(artist, city, date)
);
