-- Supabase Schema for Last-Scout

-- Artists table
CREATE TABLE IF NOT EXISTS artists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    is_core BOOLEAN DEFAULT false,
    bandsintown_patch TEXT,
    linktree_url TEXT,
    last_linktree_snapshot TEXT,
    priority_level TEXT,
    last_checked TIMESTAMP WITH TIME ZONE,
    is_discovered BOOLEAN DEFAULT false,
    genre_tags JSONB,
    status TEXT DEFAULT 'verified',
    needs_manual_verification BOOLEAN DEFAULT false,
    source TEXT
);

-- Events table
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist TEXT NOT NULL,
    city TEXT NOT NULL,
    venue TEXT NOT NULL,
    date DATE NOT NULL,
    ticket_url TEXT,
    is_recommendation BOOLEAN DEFAULT false,
    source TEXT,
    is_proximity BOOLEAN DEFAULT false,
    priority TEXT,
    discovery_source TEXT,
    UNIQUE(artist, city, date)
);

-- Locations table
CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city TEXT NOT NULL,
    country TEXT NOT NULL,
    songkick_id TEXT NOT NULL,
    scan_priority INTEGER DEFAULT 3
);

-- Similar Artists Cache table
CREATE TABLE IF NOT EXISTS similar_artists_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_artist_id BIGINT REFERENCES artists(id) ON DELETE CASCADE,
    similar_artist_name TEXT NOT NULL,
    match_score FLOAT,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Keywords table for dynamic filtering and scoring
CREATE TABLE IF NOT EXISTS keywords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word TEXT UNIQUE NOT NULL,
    category TEXT NOT NULL -- 'punk', 'blacklist', 'death'
);

-- Trigger to prevent blacklisted artists at DB level
-- Corrected for TEXT genre_tags column containing JSON strings
CREATE OR REPLACE FUNCTION validate_artist_tags()
RETURNS TRIGGER AS $func$
DECLARE
    found_keyword TEXT;
    tags_jsonb JSONB;
BEGIN
    -- Bypass validation if the artist is being blocked anyway
    IF NEW.status = 'blocked' THEN
        RETURN NEW;
    END IF;

    IF NEW.genre_tags IS NULL OR NEW.genre_tags = '' OR NEW.genre_tags = '[]' THEN
        RETURN NEW;
    END IF;

    -- Cast TEXT to JSONB for processing
    BEGIN
        tags_jsonb := NEW.genre_tags::JSONB;
    EXCEPTION WHEN OTHERS THEN
        -- If it's not valid JSON, we can't validate it this way, so we just allow it
        RETURN NEW;
    END;

    -- Check for 'death' or 'blacklist' keywords in the genre_tags JSONB array
    -- Uses \y for word boundaries to avoid false positives (e.g., 'kids' matching 'skids')
    SELECT k.word INTO found_keyword
    FROM keywords k
    WHERE k.category IN ('death', 'blacklist')
      AND EXISTS (
          SELECT 1
          FROM jsonb_array_elements_text(tags_jsonb) AS tag
          WHERE tag ~* ('\y' || k.word || '\y')
      )
    LIMIT 1;

    IF found_keyword IS NOT NULL THEN
        RAISE EXCEPTION 'Artist validation failed: blacklisted keyword found (%)', found_keyword;
    END IF;

    RETURN NEW;
END;
$func$ LANGUAGE plpgsql;

-- Always re-create the trigger to ensure it's using the latest function
DROP TRIGGER IF EXISTS artist_tags_validation ON artists;
CREATE TRIGGER artist_tags_validation
BEFORE INSERT OR UPDATE ON artists
FOR EACH ROW
EXECUTE FUNCTION validate_artist_tags();
